blank_issues_enabled: true
contact_links:
  - name: CWMS CLI
    url: https://github.com/hydrologicengineeringcenter/cwms-cli/issues
    about: Please file issues related to the cwms-cli project here.
  - name: CWMS Python
    url: https://github.com/hydrologicengineeringcenter/cwms-python/issues
    about: Please file issues related to the cwms-python library here.
  - name: CWMS Data API (CDA)
    url: https://github.com/usace/cwms-data-api/issues
    about: Please file issues related to the cwms-data-api project here.
