name: CWMS-CLI Script Issue or Feature Request
description: Request a feature related to CWMS-CLI scripts
labels: ["enhancement"]
body:
  - type: dropdown
    id: script
    attributes:
      label: CLI Script
      description: Select the script this pertains to
      options:
        - cwms-cli
        - csv2cwms
        - getusgs-measurements
        - getusgs-ratings
        - getusgs-timeseries
        - shefcritimport
        - Documentation
        - Other
    validations:
      required: true

  # FEATURE REQUEST FIELDS
  - type: textarea
    id: feature_description
    attributes:
      label: Feature Proposal
      description: What do you want to see added or changed?
      placeholder: |
        Describe the feature, its motivation, and usage examples.
        You can include code or CLI examples in code blocks.
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: REDACTED relevant log output
      description: Please copy and paste any relevant log output. Removing sensitive
        information. This will be automatically formatted into code, so no need for
        backticks.
      render: shell

  - type: textarea
    id: related_links
    attributes:
      label: Related Context or Links
      description: Include any discussions, docs, or libraries relevant to the request.
    validations:
      required: false
