from __future__ import annotations

REGULAR_INTERVAL_PARAMETERS = (
    "1Minute",
    "2Minutes",
    "3Minutes",
    "4Minutes",
    "5Minutes",
    "6Minutes",
    "8Minutes",
    "10Minutes",
    "12Minutes",
    "15Minutes",
    "20Minutes",
    "30Minutes",
    "1Hour",
    "2Hours",
    "3Hours",
    "4Hours",
    "6Hours",
    "8Hours",
    "12Hours",
    "1Day",
    "2Days",
    "3Days",
    "4Days",
    "5Days",
    "6Days",
    "1Week",
    "1Month",
    "1Year",
    "1Decade",
)

IRREGULAR_INTERVAL_PARAMETERS = (
    "0",
    "~1Minute",
    "~2Minutes",
    "~3Minutes",
    "~4Minutes",
    "~5Minutes",
    "~6Minutes",
    "~8Minutes",
    "~10Minutes",
    "~12Minutes",
    "~15Minutes",
    "~20Minutes",
    "~30Minutes",
    "~1Hour",
    "~2Hours",
    "~3Hours",
    "~4Hours",
    "~6Hours",
    "~8Hours",
    "~12Hours",
    "~1Day",
    "~2Days",
    "~3Days",
    "~4Days",
    "~5Days",
    "~6Days",
    "~1Week",
    "~1Month",
    "~1Year",
    "~1Decade",
)

ALL_INTERVAL_PARAMETERS = (
    *REGULAR_INTERVAL_PARAMETERS,
    *IRREGULAR_INTERVAL_PARAMETERS,
)
