# daily.yaml
office: "SWT"
cda_api_root: "https://cwms-data.usace.army.mil/cwms-data/"

# Either use a rolling window:
begin: "2025-09-16T00:00:00-05:00"
end: "2025-09-17T00:00:00-05:00"
# Or pin to a single instant, globally:
target_time: "0800 09/17/2025 America/Chicago"
time_epsilon_minutes: 10  # +/- window around target_time for TS picks; default 5

default_unit: "EN"
missing: "----"        # used when no value at all was found
undefined: "--NA--"    # used when a value exists but is NaN/invalid
time_zone: "America/Chicago"  # default zone for parsing target_time if zone omitted

report:
  district: "Tulsa District SWT"
  name: "Daily Morning Reservoir Report"
  logo_left: "https://www.swt-wc.usace.army.mil/images/logos/usace-logo-color.svg"
  logo_right: "https://www.swt-wc.usace.army.mil/images/logos/tulsa.png"

projects:
  - location_id: "KEYS"
    href: "https://www.swt-wc.usace.army.mil/keys.lakepage.html"
  - location_id: "SKIA"
    href: "https://www.swt-wc.usace.army.mil/skia.lakepage.html"
  - location_id: "BROK"
    href: "https://www.swt-wc.usace.army.mil/brok.lakepage.html"

columns:
  # Timeseries at a specific time
  - title: "Pool Elev (ft)"
    key: "elev_ts"
    office: "SWT"
    unit: "EN"
    precision: 2
    tsid: "{project}.Elev.Inst.1Hour.0.Ccp-Rev"
    # override the global target time for THIS column (optional):
    # target_time: "2025-09-17T08:00:00-05:00"
    # per-column render strings (optional):
    missing: "--"
    undefined: "~~~~.~~"
    href: "https://water.usace.army.mil/office/{office}/ts?name={tsid}"

  # Level identifier (no sampling window; we just read the level)
  - title: "Top of Conservation (ft)"
    key: "top_cons"
    office: "SWT"
    unit: "ft"
    precision: 2
    level: "{project}.Elev.Inst.0.Top of Conservation"
    # optional per column overrides
    undefined: "n/a"
