# daily.yaml
office: "SWT"
cda_api_root: "https://cwms-data.usace.army.mil/cwms-data/"

# Either use a rolling window:
begin: "2025-09-16T00:00:00-05:00"
end: "2025-09-17T00:00:00-05:00"
# Or pin to a single instant, globally:
target_time: "0800 09/17/2025 America/Chicago"

default_unit: "EN"
missing: "----"        # used when no value at all was found
undefined: "--NA--"    # used when a value exists but is NaN/invalid
time_zone: "America/Chicago"  # default zone for parsing target_time if zone omitted

report:
  district: "Tulsa District SWT"
  name: "Daily Morning Reservoir Report"
  logo_left: "https://www.swt-wc.usace.army.mil/images/logos/usace-logo-color.svg"
  logo_right: "https://www.swt-wc.usace.army.mil/images/logos/tulsa.png"

projects:
  # - location_id: "SKIA"
  #   href: "https://www.swt-wc.usace.army.mil/skia.lakepage.html"
  # - location_id: "BROK"
  #   href: "https://www.swt-wc.usace.army.mil/brok.lakepage.html"
  # - location_id: "ALTU"
  #   href: "https://www.swt-wc.usace.army.mil/ALTU.lakepage.html"
  # - location_id: "ARBU"
  #   href: "https://www.swt-wc.usace.army.mil/ARBU.lakepage.html"
  # - location_id: "ARCA"
  #   href: "https://www.swt-wc.usace.army.mil/ARCA.lakepage.html"
  # - location_id: "BIGH"
  #   href: "https://www.swt-wc.usace.army.mil/BIGH.lakepage.html"
  # - location_id: "BIRC"
  #   href: "https://www.swt-wc.usace.army.mil/BIRC.lakepage.html"
  # - location_id: "BROK"
  #   href: "https://www.swt-wc.usace.army.mil/BROK.lakepage.html"
  # - location_id: "CANT"
  #   href: "https://www.swt-wc.usace.army.mil/CANT.lakepage.html"
  # - location_id: "CHEN"
  #   href: "https://www.swt-wc.usace.army.mil/CHEN.lakepage.html"
  # - location_id: "FCOB"
  #   href: "https://www.swt-wc.usace.army.mil/FCOB.lakepage.html"
  # - location_id: "COPA"
  #   href: "https://www.swt-wc.usace.army.mil/COPA.lakepage.html"
  # - location_id: "COUN"
  #   href: "https://www.swt-wc.usace.army.mil/COUN.lakepage.html"
  # - location_id: "DENI"
  #   href: "https://www.swt-wc.usace.army.mil/DENI.lakepage.html"
  # - location_id: "ELDR"
  #   href: "https://www.swt-wc.usace.army.mil/ELDR.lakepage.html"
  # - location_id: "ELKC"
  #   href: "https://www.swt-wc.usace.army.mil/ELKC.lakepage.html"
  # - location_id: "EUFA"
  #   href: "https://www.swt-wc.usace.army.mil/EUFA.lakepage.html"
  # - location_id: "FALL"
  #   href: "https://www.swt-wc.usace.army.mil/FALL.lakepage.html"
  # - location_id: "FCOB"
  #   href: "https://www.swt-wc.usace.army.mil/FCOB.lakepage.html"
  - location_id: "FGIB"
    href: "https://www.swt-wc.usace.army.mil/FGIB.lakepage.html"
  # - location_id: "FOSS"
  #   href: "https://www.swt-wc.usace.army.mil/FOSS.lakepage.html"
  # - location_id: "FSUP"
  #   href: "https://www.swt-wc.usace.army.mil/FSUP.lakepage.html"
  # - location_id: "GSAL"
  #   href: "https://www.swt-wc.usace.army.mil/GSAL.lakepage.html"
  # - location_id: "HEYB"
  #   href: "https://www.swt-wc.usace.army.mil/HEYB.lakepage.html"
  # - location_id: "HUDS"
  #   href: "https://www.swt-wc.usace.army.mil/HUDS.lakepage.html"
  # - location_id: "HUGO"
  #   href: "https://www.swt-wc.usace.army.mil/HUGO.lakepage.html"
  # - location_id: "HULA"
  #   href: "https://www.swt-wc.usace.army.mil/HULA.lakepage.html"
  # - location_id: "JOHN"
  #   href: "https://www.swt-wc.usace.army.mil/JOHN.lakepage.html"
  # - location_id: "KAWL"
  #   href: "https://www.swt-wc.usace.army.mil/KAWL.lakepage.html"
  # - location_id: "KEMP"
  #   href: "https://www.swt-wc.usace.army.mil/KEMP.lakepage.html"
  # - location_id: "KEYS"
  #   href: "https://www.swt-wc.usace.army.mil/KEYS.lakepage.html"
  # - location_id: "MARI"
  #   href: "https://www.swt-wc.usace.army.mil/MARI.lakepage.html"
  # - location_id: "MCGE"
  #   href: "https://www.swt-wc.usace.army.mil/MCGE.lakepage.html"
  # - location_id: "MERE"
  #   href: "https://www.swt-wc.usace.army.mil/MERE.lakepage.html"
  # - location_id: "OOLO"
  #   href: "https://www.swt-wc.usace.army.mil/OOLO.lakepage.html"
  # - location_id: "PATM"
  #   href: "https://www.swt-wc.usace.army.mil/PATM.lakepage.html"
  # - location_id: "PENS"
  #   href: "https://www.swt-wc.usace.army.mil/PENS.lakepage.html"
  # - location_id: "PINE"
  #   href: "https://www.swt-wc.usace.army.mil/PINE.lakepage.html"
  # - location_id: "SARD"
  #   href: "https://www.swt-wc.usace.army.mil/SARD.lakepage.html"
  # - location_id: "SKIA"
  #   href: "https://www.swt-wc.usace.army.mil/SKIA.lakepage.html"
  # - location_id: "TENK"
  #   href: "https://www.swt-wc.usace.army.mil/TENK.lakepage.html"
  # - location_id: "THUN"
  #   href: "https://www.swt-wc.usace.army.mil/THUN.lakepage.html"
  # - location_id: "TOMS"
  #   href: "https://www.swt-wc.usace.army.mil/TOMS.lakepage.html"
  # - location_id: "TORO"
  #   href: "https://www.swt-wc.usace.army.mil/TORO.lakepage.html"
  # - location_id: "WAUR"
  #   href: "https://www.swt-wc.usace.army.mil/WAUR.lakepage.html"
  # - location_id: "WIST"
  #   href: "https://www.swt-wc.usace.army.mil/WIST.lakepage.html"

header:
  project:
    text: "Reservoir"   # text in the far-left header cell
    classes: ""         # optional extra classes
    align: center       # optional: left|center|right
  rows:
      # Header row 1
    -   -
          text: "Pool Elevation"
          colspan: 2
        - text: "Pool Limits"
          colspan: 2
        - text: "Pool Occupied Storage"
          colspan: 3
        - text: "8AM Status (cfs)"
          colspan: 3
        - text: "Previous 24Hr Average (cfs)"
          colspan: 3
        - text: "Precip (in)"
          align: center
      # Header row 2
    -   - text: ""
          rowspan: 2
        - text: "8AM <br>Current"
          rowspan: 2
        - text: "8AM <br>Prev"
          rowspan: 2
        - text: "Top Of"
          colspan: 2
        - text: "(%)"
          rowspan: 2
        - text: "C/F"
          rowspan: 2
        - text: "(ac-ft)"
          rowspan: 2
        - text: "Total Release"
          rowspan: 2
        - text: "Power Release"
          rowspan: 2
        - text: "Inflow"
          rowspan: 2
        - text: "Total Release"
          rowspan: 2
        - text: "Power Release"
          rowspan: 2
        - text: "Inflow"
          rowspan: 2
        - text: "24Hr"
          rowspan: 2
      # Header row 3
    -   - text: "Pool Elev (ft)"
        - text: "Tailwater (ft)"

columns:
  # Timeseries at a specific time
  - title: "Pool Elev (ft)"
    key: "elev_ts"
    office: "SWT"
    unit: "EN"
    precision: 2
    tsid: "{project}.Elev.Inst.1Hour.0.Ccp-Rev"
    # override the global target time for THIS column (optional):
    begin: "today 0800"
    end: "today 0800"
    # per-column render strings (optional):
    missing: "--"
    undefined: "~~~~.~~"
    href: "https://water.usace.army.mil/office/{office}/ts?name={tsid}"
  - title: "Pool Elev (ft)"
    key: "elev_ts"
    office: "SWT"
    unit: "EN"
    precision: 2
    tsid: "{project}.Elev.Inst.1Hour.0.Ccp-Rev"
    begin: "yesterday 0800 America/Chicago"
    end: "yesterday 0800 America/Chicago"
    # override the global target time for THIS column (optional):
    target_time: "2025-09-21T08:00:00-05:00"
    # per-column render strings (optional):
    missing: "--"
    undefined: "~~~~.~~"
    href: "https://water.usace.army.mil/office/{office}/ts?name={tsid}"
  # Level identifier (no sampling window; we just read the level)
  - title: "Top of Conservation (ft)"
    key: "top_cons"
    office: "SWT"
    unit: "ft"
    precision: 2
    level: "{project}.Elev.Inst.0.Top of Conservation"
    # optional per column overrides
    undefined: "n/a"
