from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

try:
    import tomllib
except ModuleNotFoundError:  # pragma: no cover
    import tomli as tomllib  # type: ignore[no-redef]


ROOT = Path(__file__).resolve().parents[1]
MAINTAINERS_TOML = ROOT / "maintainers.toml"
PYPROJECT_TOML = ROOT / "pyproject.toml"
CODEOWNERS = ROOT / ".github" / "CODEOWNERS"


def load_maintainers() -> dict:
    with MAINTAINERS_TOML.open("rb") as fh:
        return tomllib.load(fh)


def render_poetry_authors(data: dict) -> list[str]:
    people = data["people"]
    author_keys = data["poetry"]["authors"]
    return [f'{people[key]["name"]} <{people[key]["email"]}>' for key in author_keys]


def render_pyproject(data: dict, content: str) -> str:
    authors = render_poetry_authors(data)
    authors_line = "authors = [" + ", ".join(f'"{author}"' for author in authors) + "]"

    if re.search(r"^authors\s*=\s*\[[^\n]*\]$", content, flags=re.M) is None:
        raise RuntimeError("Unable to find [tool.poetry].authors in pyproject.toml")
    return re.sub(
        r"^authors\s*=\s*\[[^\n]*\]$",
        authors_line,
        content,
        count=1,
        flags=re.M,
    )


def sync_pyproject(data: dict) -> None:
    content = PYPROJECT_TOML.read_text(encoding="utf-8")
    updated = render_pyproject(data, content)
    PYPROJECT_TOML.write_text(updated, encoding="utf-8")


def render_codeowners(data: dict) -> str:
    people = data["people"]
    lines = [
        "# DO NOT EDIT THIS FILE MANUALLY.",
        "# Generated from maintainers.toml by scripts/sync_ownership.py.",
        "# Update maintainers.toml, then rerun the sync script.",
        "",
    ]

    for rule in data["codeowners"]["rule"]:
        owners = " ".join(people[key]["email"] for key in rule["owners"])
        line = f'{rule["pattern"]} {owners}'
        comment = rule.get("comment")
        if comment:
            line = f"{line}  # {comment}"
        lines.append(line)

    lines.append("")
    return "\n".join(lines)


def sync_codeowners(data: dict) -> None:
    CODEOWNERS.write_text(render_codeowners(data), encoding="utf-8")


def check_file(path: Path, expected: str) -> bool:
    current = path.read_text(encoding="utf-8") if path.exists() else ""
    if current == expected:
        return True
    print(
        f"{path.relative_to(ROOT)} is out of sync with maintainers.toml",
        file=sys.stderr,
    )
    return False


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Sync ownership metadata into generated project files."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Verify generated files are up to date without writing changes.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    data = load_maintainers()
    pyproject_content = PYPROJECT_TOML.read_text(encoding="utf-8")
    expected_pyproject = render_pyproject(data, pyproject_content)
    expected_codeowners = render_codeowners(data)
    current_codeowners = (
        CODEOWNERS.read_text(encoding="utf-8") if CODEOWNERS.exists() else ""
    )

    if args.check:
        ok = True
        ok = check_file(PYPROJECT_TOML, expected_pyproject) and ok
        ok = check_file(CODEOWNERS, expected_codeowners) and ok
        if ok:
            print("Ownership files are in sync.")
        raise SystemExit(0 if ok else 1)

    updated_files: list[str] = []
    if pyproject_content != expected_pyproject:
        PYPROJECT_TOML.write_text(expected_pyproject, encoding="utf-8")
        updated_files.append(str(PYPROJECT_TOML.relative_to(ROOT)))

    if current_codeowners != expected_codeowners:
        CODEOWNERS.write_text(expected_codeowners, encoding="utf-8")
        updated_files.append(str(CODEOWNERS.relative_to(ROOT)))

    if updated_files:
        print("Updated ownership files:")
        for path in updated_files:
            print(f"- {path}")
    else:
        print("Ownership files already up to date.")


if __name__ == "__main__":
    main()
