from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

try:
    import tomllib
except ModuleNotFoundError:  # pragma: no cover
    import tomli as tomllib  # type: ignore[no-redef]


ROOT = Path(__file__).resolve().parents[1]
MAINTAINERS_TOML = ROOT / "maintainers.toml"
PYPROJECT_TOML = ROOT / "pyproject.toml"
CODEOWNERS = ROOT / ".github" / "CODEOWNERS"
OWNERSHIP_DATA = ROOT / "cwmscli" / "_generated" / "ownership_data.py"
DOCS_MAINTAINERS_DIR = ROOT / "docs" / "_generated" / "maintainers"


def load_maintainers() -> dict:
    with MAINTAINERS_TOML.open("rb") as fh:
        return tomllib.load(fh)


def render_poetry_authors(data: dict) -> list[str]:
    people = data["people"]
    author_keys = data["poetry"]["authors"]
    return [f'{people[key]["name"]} <{people[key]["email"]}>' for key in author_keys]


def render_pyproject(data: dict, content: str) -> str:
    authors = render_poetry_authors(data)
    authors_line = "authors = [" + ", ".join(f'"{author}"' for author in authors) + "]"

    if re.search(r"^authors\s*=\s*\[[^\n]*\]$", content, flags=re.M) is None:
        raise RuntimeError("Unable to find [tool.poetry].authors in pyproject.toml")
    return re.sub(
        r"^authors\s*=\s*\[[^\n]*\]$",
        authors_line,
        content,
        count=1,
        flags=re.M,
    )


def render_codeowners(data: dict) -> str:
    people = data["people"]
    lines = [
        "# DO NOT EDIT THIS FILE MANUALLY.",
        "# Generated from maintainers.toml by scripts/sync_ownership.py.",
        "# Update maintainers.toml, then rerun the sync script.",
        "",
    ]

    for rule in data["codeowners"]["rule"]:
        owners = " ".join(people[key]["email"] for key in rule["owners"])
        line = f'{rule["pattern"]} {owners}'
        comment = rule.get("comment")
        if comment:
            line = f"{line}  # {comment}"
        lines.append(line)

    lines.append("")
    return "\n".join(lines)


def render_cli_ownership_data(data: dict) -> str:
    people = data["people"]
    default_keys = data["cli"]["default"]
    command_map = data["cli"]["commands"]

    payload = {
        "default": [
            {"name": people[key]["name"], "email": people[key]["email"]}
            for key in default_keys
        ],
        "commands": {
            command: [
                {"name": people[key]["name"], "email": people[key]["email"]}
                for key in owner_keys
            ]
            for command, owner_keys in command_map.items()
        },
    }

    return (
        "# DO NOT EDIT THIS FILE MANUALLY.\n"
        "# Generated from maintainers.toml by scripts/sync_ownership.py.\n\n"
        f"OWNERSHIP_DATA = {json.dumps(payload, indent=4, sort_keys=True)}\n"
    )


def render_docs_include(data: dict, command_path: str) -> str:
    people = data["people"]
    command_owners = data["cli"]["commands"].get(command_path, data["cli"]["default"])
    names = ", ".join(people[key]["name"] for key in command_owners)
    return f".. note::\n\n   Maintainers: {names}\n"


def expected_generated_files(data: dict) -> dict[Path, str]:
    generated = {
        CODEOWNERS: render_codeowners(data),
        OWNERSHIP_DATA: render_cli_ownership_data(data),
    }
    for stem, command_path in data["docs"]["pages"].items():
        generated[DOCS_MAINTAINERS_DIR / f"{stem}.inc"] = render_docs_include(
            data, command_path
        )
    return generated


def check_file(path: Path, expected: str) -> bool:
    current = path.read_text(encoding="utf-8") if path.exists() else ""
    if current == expected:
        return True
    print(
        f"{path.relative_to(ROOT)} is out of sync with maintainers.toml",
        file=sys.stderr,
    )
    return False


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Sync ownership metadata into generated project files."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Verify generated files are up to date without writing changes.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    data = load_maintainers()
    pyproject_content = PYPROJECT_TOML.read_text(encoding="utf-8")
    expected_pyproject = render_pyproject(data, pyproject_content)
    generated_files = expected_generated_files(data)

    if args.check:
        ok = True
        ok = check_file(PYPROJECT_TOML, expected_pyproject) and ok
        for path, expected in generated_files.items():
            ok = check_file(path, expected) and ok
        if ok:
            print("Ownership files are in sync.")
        raise SystemExit(0 if ok else 1)

    updated_files: list[str] = []
    if pyproject_content != expected_pyproject:
        PYPROJECT_TOML.write_text(expected_pyproject, encoding="utf-8")
        updated_files.append(str(PYPROJECT_TOML.relative_to(ROOT)))

    for path, expected in generated_files.items():
        current = path.read_text(encoding="utf-8") if path.exists() else ""
        if current == expected:
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(expected, encoding="utf-8")
        updated_files.append(str(path.relative_to(ROOT)))

    if updated_files:
        print("Updated ownership files:")
        for path in updated_files:
            print(f"- {path}")
    else:
        print("Ownership files already up to date.")


if __name__ == "__main__":
    main()
