# DO NOT EDIT THIS FILE MANUALLY.
# Generated from maintainers.toml by scripts/sync_ownership.py.

OWNERSHIP_DATA = {
    "commands": {
        "cwms-cli blob": [
            {
                "email": "charles.r.graham@usace.army.mil",
                "name": "Charles Graham"
            }
        ],
        "cwms-cli csv2cwms": [
            {
                "email": "charles.r.graham@usace.army.mil",
                "name": "Charles Graham"
            }
        ],
        "cwms-cli load": [
            {
                "email": "charles.r.graham@usace.army.mil",
                "name": "Charles Graham"
            },
            {
                "email": "eric.v.novotny@usace.army.mil",
                "name": "Eric Novotny"
            }
        ],
        "cwms-cli shefcritimport": [
            {
                "email": "eric.v.novotny@usace.army.mil",
                "name": "Eric Novotny"
            }
        ],
        "cwms-cli update": [
            {
                "email": "charles.r.graham@usace.army.mil",
                "name": "Charles Graham"
            }
        ],
        "cwms-cli usgs": [
            {
                "email": "eric.v.novotny@usace.army.mil",
                "name": "Eric Novotny"
            }
        ]
    },
    "default": [
        {
            "email": "charles.r.graham@usace.army.mil",
            "name": "Charles Graham"
        },
        {
            "email": "eric.v.novotny@usace.army.mil",
            "name": "Eric Novotny"
        }
    ]
}
